[package]
name = "cherry_app"
version = "0.0.6"
authors = [
	"Kacper Skrzynski <adamn.zxc@gmial.com>",
	" <>",
	" <>",
	" <>",
	" <>"
]
build = "build.rs"

[dependencies]
rocket = "*"
rocket_codegen = "*"

[build-dependencies]
inotify = "0.4.2"
rsass = "0.3.4"
